
POPULATION_SIZE = 20
VERBOSE = 1
W_POS = 1
W_NEG = 10
LOG_LEVEL = 1
ROOT_DIR = "."
OUTPUT_DIR = "output/"
TEMP_DIR = "temp/"
CANDIDATE_INDEX = 0
CROSSOVER_PROBABILITY = 1.0
DROP_PLAUSIBLE = True

STOP_CRIT = "gen"
MAX_GENERATIONS = 30
MAX_SIZE = 1000
MAX_TIME = 100000
